theme: jekyll-theme-minimal
title: gothicLolita299's homepage
description: GitHub Pages example for promoting a project
url: https://gothiclolita229.github.io/linaresl1836.github.io/


github_username: gothiclolita229
